### ISSUE TITLE
Suggest features for the bot

### ISSUE THREAD

**Issue by reapedjuggler** [Knuth-Programming-Hub/KLE-bot#13]
Currently, the bot has some limited features, suggest some :)

Directions:
Make a `features.md` file and keep updating it.

**Comment by hemant2132** [comment]
@reapedjuggler I think we can close this issue, since we now have [Discussions](https://github.com/Knuth-Programming-Hub/KLE-bot/discussions).

**Comment by reapedjuggler** [comment]
Yeah sure :)
